apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-services
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30s"  # Increase connect timeout
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30s"     # Increase send timeout
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30s"     # Increase read timeout
spec:
  ingressClassName: nginx
  rules:
  - host: service.cloudaes.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-service-east
            port:
              number: 4143
